### ISSUE TITLE
Propromo monorepo for improved sprint reviews.

### ISSUE THREAD

**Issue by jonasfroeller** [propromo-software/propromo#2]

**Comment by SIMULATAN** [comment]
Things to do:
- [x] add variable for monorepo name (https://github.com/organizations/propromo-software/settings/variables/actions)
- [x] create deploy key for repos in monorepo

**Comment by SIMULATAN** [comment]
![screenshot of monorepo-test](https://github.com/user-attachments/assets/e1f7807b-3f54-4cc7-a3d1-b4ff881204c0)
works :D

**Comment by jonasfroeller** [comment]
https://github.com/propromo-software/propromo
